### ISSUE TITLE
Parsear cuestionarios a json

### ISSUE THREAD

**Issue by NattoV** [rdelgadov/CEDS#18]
Parsear los cuestionarios de los cursos a formato json definido por:

``` 
{ 
  id : numero, 
  tipo:["unica", "multiple", "ptje"],
  texto: "Soy una pregunta?", 
  respuestas:["Soy una respuesta", "Yo no "]
}
```

**Comment by rdelgadov** [comment]
En ingles serían:

´´´
{ 
  id : number, 
  type:["unique", "multiple", "points"],
  text: "Soy una pregunta?", 
  answer:["Soy una respuesta", "Yo no "]
}
´´´

**Comment by gyahu** [comment]
Le agregué un atributo score, para cada respuesta
